name: style check

on:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: .

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          cache: 'pip'
          cache-dependency-path: '**/setup.cfg'
      - name: Install package with dependencies
        run: pip install -e ".[dev]"
        if: steps.python-cache.outputs.cache-hit != 'true'
      - name: Run black
        run: black src --check --diff
      - name: Check that documentation can be built
        run: tox -e docs
