name: unit tests

on:
  push:
    branches:
      - "**"
    paths:
      - 'undate/**'
      - 'tests/**'
  pull_request:

jobs:
  python-unit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.8", "3.9", "3.10", "3.11"]
    defaults:
      run:
        working-directory: .

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
          cache: 'pip'
          cache-dependency-path: '**/setup.py'
      - name: Install package with dependencies
        run: pip install -e ".[dev]"
        if: steps.python-cache.outputs.cache-hit != 'true'
      - name: Run unit tests with slipcover for code coverage
        run: python -m slipcover --json --out coverage.json -m pytest
      - name: Upload test coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.json
