name: unit tests

on:
  push:
    branches:
      - "**"
    paths:
      - 'undate/**'
      - 'tests/**'
  pull_request:

env:
  COV_PYTHON_VERSION: "3.9"

jobs:
  python-unit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.8", "3.9", "3.10", "3.11"]
    defaults:
      run:
        working-directory: .

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
          cache: 'pip'
          cache-dependency-path: '**/setup.py'
      - name: Install package with dependencies
        run: pip install -e ".[dev]"
        if: steps.python-cache.outputs.cache-hit != 'true'

      # for all versions but the one we use for code coverage, run normally
      - name: Run unit tests normally
        run: pytest
        if: ${{ matrix.python != env.COV_PYTHON_VERSION }}

      # run code coverage in one version only
        run: pytest --cov=./ --cov-report=xml
        if: ${{ matrix.python == env.COV_PYTHON_VERSION }}
      - name: Upload test coverage to Codecov
        uses: codecov/codecov-action@v3
        if: ${{ matrix.python == env.COV_PYTHON_VERSION }}
